### ISSUE TITLE
Remove extra element in list in RecordStudio component

### ISSUE THREAD

**Issue by in43sh** [MajesticBay/basement-studio#2]
in RecordStudio there are 3 cards and lists inside those cards have a different amount of elements in Ukrainian and English: in English 2 cards each have 2 elements and in Ukrainian those cards have 3 elements. So, those 2 cards show an extra dot as there will be an extra element.

**Comment by in43sh** [comment]
https://github.com/MajesticBay/basement-studio/blob/19c49865979c9dfd4141fbda6d301c60a6f1e177/src/components/sections/RecordStudio.js#L64

**Comment by in43sh** [comment]
translation files
https://github.com/MajesticBay/basement-studio/blob/19c49865979c9dfd4141fbda6d301c60a6f1e177/public/i18n/translations/en.json#L15
https://github.com/MajesticBay/basement-studio/blob/19c49865979c9dfd4141fbda6d301c60a6f1e177/public/i18n/translations/ua.json#L15

**Comment by in43sh** [comment]
@shweps13

**Comment by shweps13** [comment]
Fixed with [acc37b2580594e408d11209dbab2b3021c253033](https://github.com/MajesticBay/basement-studio/commit/acc37b2580594e408d11209dbab2b3021c253033)
